- boards.md
> Update the boards

- README.md
- meetings.md
- tools.md
- work-cycles.md
> Filling out the handbook

- runner.md
Also, add tip about bookmarked search
> Create a separate "initial setup" step for runner role

- scsb.md
> Starting some new SCSB documentation

- reshare.md
Resolves pulibrary/orangelight#3207
> Reshare api docs

- boards.md
> add meaning of points

- Javascript/JavascriptBestPractices/Comments.md
- Javascript/JavascriptBestPractices/Contents.md
- Javascript/JavascriptBestPractices/Destructuring.md
- Javascript/JavascriptBestPractices/Functions.md
- Javascript/JavascriptBestPractices/Hoisting.md
- Javascript/JavascriptBestPractices/Linters.md
- Javascript/JavascriptBestPractices/NameConventions.md
- Javascript/JavascriptBestPractices/Recursion.md
- Javascript/JavascriptBestPractices/References.md
- Javascript/JavascriptBestPractices/Semicolons.md
- Javascript/JavascriptBestPractices/Testing.md
- Javascript/JavascriptBestPractices/Variables.md
> Start JS best practices

- Accessibility/accessibility_best_practices.md
- Creating new applications/accessibility.md
Start accessibility best practices documentation
Jane Sandberg <sandbergja@users.noreply.github.com>
> Start new application, include accessibility

- dubbot.md
> Adding my notes from the dubbot meeting

- .github/ISSUE_TEMPLATE/onboarding.md
Inspired by https://github.com/pulibrary/rdss-handbook/blob/main/onboarding.md -- thanks, RDSS and @bess in particular!
> add .gitmessage to onboarding template

- .github/ISSUE_TEMPLATE/onboarding.md
- runner.md
Thanks, @regineheberlein!  Let me know if this gets at your recommendations.
> Incorporate feedback from Regine to the onboarding checklist

- .github/ISSUE_TEMPLATE/onboarding.md
@maxkadel recommended being clearer about which parts of the pul-it-handbook and dacs_handbooks new team members need to read -- thanks, @maxkadel !
> Incorporate feedback into onboarding template

- issues-and-labels.md
Partially based on conversations with @lizgarciao and @ishasinha1 -- thanks to both of you!
closes #77
> Add additional context to Issues and Labels page

- Creating new applications/accessibility.md
- Creating new applications/rails.md
Based on the README of pulibrary/rails-template -- thanks for maintaining that, DLS!
> Adding procedures for creating a new rails application

- Creating new applications/rails.md
It causes bugs, and provides little benefit
> Don't use spring for new rails applications

- README.md
- incidents.md
- meetings.md
> Use Ops team rather than DevOps team

- Accessibility/audit_procedure.md
part of #121 
Update the audit procedure with a link to the accessibility audits drive.
> Update audit_procedure.md part of #121

- Accessibility/accessibility_audits.md
> Add document with a link to the accessibility audits drive 

- .github/ISSUE_TEMPLATE/onboarding.md
> Update with new confluence links

- .github/ISSUE_TEMPLATE/onboarding.md
- accounts.md
> Reviewed the onboarding and small updates

- meetings.md
> Add quarterly sprint meeting information, update links. 

- .github/ISSUE_TEMPLATE/weekly_deployments.md
> Created a template for deployments

- .github/ISSUE_TEMPLATE/workcycle_playbooks_run.md
> [#211] Create an issue template to list the application/playbooks that need to run in every workcycle

- alma.md
We found this while experimenting with the Vale documentation linter
> Fix typo in alma.md

- board_manager.md
- runner.md
Per team conversation on 11/11.
> Update runner role, add board manager.

- .github/ISSUE_TEMPLATE/workcycle_build_and_deploy.md
* Update Urls for byzantine
* Make it clear that we do this every week starting on Monday, rather than every work cycle (see [meeting notes](https://docs.google.com/document/d/1O7f8rXTDRKALfB7PoTcgI3hjI4qSIUz80Y6I0Qejjds/edit?tab=t.0#heading=h.9okr27kqpdug))
> Updates to the deployment issue template

- meetings.md
- work-cycles.md
Update these to reflect current practices and include goals for standing meetings.
> Updated Work Cycle and Meeting Documentation

- .github/ISSUE_TEMPLATE/workcycle_build_and_deploy.md
Update the build and deploy template. Remove playbooks that run daily in ansible tower.
> Update the build and deploy template. Remove playbooks that run daily in ansible tower.

- continuous_deploy.md
Connected to https://github.com/pulibrary/orangelight/issues/4879
> Add documentation on adding a continuous deploy pipeline to CircleCI

- .gitignore
- research/in-browser_voice_activity_detection/in-browser_voice_activity_detection.md
- research/in-browser_voice_activity_detection/libfvad-worklet.js
- research/in-browser_voice_activity_detection/no-processing-worklet.js
- research/in-browser_voice_activity_detection/setup-vad-tester.sh
- research/in-browser_voice_activity_detection/silero-inference.js
- research/in-browser_voice_activity_detection/silero-worklet.js
- research/in-browser_voice_activity_detection/vad-tester.html
- research/in-browser_voice_activity_detection/vad-tester.js
> Add results of first experiment with in-browser Voice Activity Detection

- .github/ISSUE_TEMPLATE/workcycle_build_and_deploy.md
* remove applications that are scheduled to deploy through ansible tower.
> Update deployment github template
